### ISSUE TITLE
Package Maintainer

### ISSUE THREAD

**Issue by maennchen** [jshmrtn/iona#18]
Follow up from https://github.com/CargoSense/iona/pull/17#issuecomment-558161077

I'd be willing to take over ownership of that repository and try to push it to stable. If you're agreeing to it, I'd propose to move the repository to the `jshmrtn` organisation and the hex.pm ownership to the user `maennchen`.

I'll be using this package to build some complex documents for a customer of ours and will contribute back bugfixes / tests etc. and hopefully release it stable ( `v1`) afterwards.

**Comment by benwilson512** [comment]
I'm on board. If we were using this ourselves to some extent as well I'd propose just adding you as a maintainer, but we haven't used this in a very long time and I'd rather free it up to someone who will be able to provide it with proper attention. I'll make the transfer shortly.

**Comment by benwilson512** [comment]
@bruce I'll actually need you to add @maennchen on hex, you're the only owner on the package.

**Comment by benwilson512** [comment]
@maennchen I can't actually do the transfer since I don't have the rights to create a repo within your org. Instead I simply added you as an admin to this repository, so you should be able to do the transfer yourself after you accept.

**Comment by maennchen** [comment]
@benwilson512 Thanks, that worked.

Could you fork it back and put a notice up that the repo has been moved?

**Comment by benwilson512** [comment]
Done! Hopefully we'll hear from Bruce soon WRT hex.

**Comment by maennchen** [comment]
TODO's from my side:

* [ ] Push new release to hex correcting the GitHub Links
* [ ] Change Badge URL's to the new repo

**Comment by bruce** [comment]
I'll take care of the hex addition shortly

**Comment by bruce** [comment]
✅   Done

```
mix hex.owner add iona maennchen
Adding owner maennchen with ownership level full to iona
```

Thanks for taking this over, maennchen. Feel free to remove my ownership when you're ready.

**Comment by benwilson512** [comment]
Thanks @bruce and @maennchen!
